// Code generated by ent, DO NOT EDIT.

package userthreadlike

import (
	"server/infrastructure/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// UserId applies equality check predicate on the "userId" field. It's identical to UserIdEQ.
func UserId(v int) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.FieldEQ(FieldUserId, v))
}

// ThreadId applies equality check predicate on the "threadId" field. It's identical to ThreadIdEQ.
func ThreadId(v int) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.FieldEQ(FieldThreadId, v))
}

// LikedAt applies equality check predicate on the "likedAt" field. It's identical to LikedAtEQ.
func LikedAt(v time.Time) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.FieldEQ(FieldLikedAt, v))
}

// UserIdEQ applies the EQ predicate on the "userId" field.
func UserIdEQ(v int) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.FieldEQ(FieldUserId, v))
}

// UserIdNEQ applies the NEQ predicate on the "userId" field.
func UserIdNEQ(v int) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.FieldNEQ(FieldUserId, v))
}

// UserIdIn applies the In predicate on the "userId" field.
func UserIdIn(vs ...int) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.FieldIn(FieldUserId, vs...))
}

// UserIdNotIn applies the NotIn predicate on the "userId" field.
func UserIdNotIn(vs ...int) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.FieldNotIn(FieldUserId, vs...))
}

// ThreadIdEQ applies the EQ predicate on the "threadId" field.
func ThreadIdEQ(v int) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.FieldEQ(FieldThreadId, v))
}

// ThreadIdNEQ applies the NEQ predicate on the "threadId" field.
func ThreadIdNEQ(v int) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.FieldNEQ(FieldThreadId, v))
}

// ThreadIdIn applies the In predicate on the "threadId" field.
func ThreadIdIn(vs ...int) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.FieldIn(FieldThreadId, vs...))
}

// ThreadIdNotIn applies the NotIn predicate on the "threadId" field.
func ThreadIdNotIn(vs ...int) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.FieldNotIn(FieldThreadId, vs...))
}

// LikedAtEQ applies the EQ predicate on the "likedAt" field.
func LikedAtEQ(v time.Time) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.FieldEQ(FieldLikedAt, v))
}

// LikedAtNEQ applies the NEQ predicate on the "likedAt" field.
func LikedAtNEQ(v time.Time) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.FieldNEQ(FieldLikedAt, v))
}

// LikedAtIn applies the In predicate on the "likedAt" field.
func LikedAtIn(vs ...time.Time) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.FieldIn(FieldLikedAt, vs...))
}

// LikedAtNotIn applies the NotIn predicate on the "likedAt" field.
func LikedAtNotIn(vs ...time.Time) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.FieldNotIn(FieldLikedAt, vs...))
}

// LikedAtGT applies the GT predicate on the "likedAt" field.
func LikedAtGT(v time.Time) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.FieldGT(FieldLikedAt, v))
}

// LikedAtGTE applies the GTE predicate on the "likedAt" field.
func LikedAtGTE(v time.Time) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.FieldGTE(FieldLikedAt, v))
}

// LikedAtLT applies the LT predicate on the "likedAt" field.
func LikedAtLT(v time.Time) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.FieldLT(FieldLikedAt, v))
}

// LikedAtLTE applies the LTE predicate on the "likedAt" field.
func LikedAtLTE(v time.Time) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.FieldLTE(FieldLikedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserThreadLike {
	return predicate.UserThreadLike(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, UserColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserThreadLike {
	return predicate.UserThreadLike(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasThread applies the HasEdge predicate on the "thread" edge.
func HasThread() predicate.UserThreadLike {
	return predicate.UserThreadLike(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, ThreadColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, ThreadTable, ThreadColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasThreadWith applies the HasEdge predicate on the "thread" edge with a given conditions (other predicates).
func HasThreadWith(preds ...predicate.Thread) predicate.UserThreadLike {
	return predicate.UserThreadLike(func(s *sql.Selector) {
		step := newThreadStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserThreadLike) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserThreadLike) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserThreadLike) predicate.UserThreadLike {
	return predicate.UserThreadLike(sql.NotPredicates(p))
}
