// Code generated by ent, DO NOT EDIT.

package userboardlike

import (
	"server/infrastructure/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// UserId applies equality check predicate on the "userId" field. It's identical to UserIdEQ.
func UserId(v int) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.FieldEQ(FieldUserId, v))
}

// BoardId applies equality check predicate on the "boardId" field. It's identical to BoardIdEQ.
func BoardId(v int) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.FieldEQ(FieldBoardId, v))
}

// LikedAt applies equality check predicate on the "likedAt" field. It's identical to LikedAtEQ.
func LikedAt(v time.Time) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.FieldEQ(FieldLikedAt, v))
}

// UserIdEQ applies the EQ predicate on the "userId" field.
func UserIdEQ(v int) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.FieldEQ(FieldUserId, v))
}

// UserIdNEQ applies the NEQ predicate on the "userId" field.
func UserIdNEQ(v int) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.FieldNEQ(FieldUserId, v))
}

// UserIdIn applies the In predicate on the "userId" field.
func UserIdIn(vs ...int) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.FieldIn(FieldUserId, vs...))
}

// UserIdNotIn applies the NotIn predicate on the "userId" field.
func UserIdNotIn(vs ...int) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.FieldNotIn(FieldUserId, vs...))
}

// BoardIdEQ applies the EQ predicate on the "boardId" field.
func BoardIdEQ(v int) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.FieldEQ(FieldBoardId, v))
}

// BoardIdNEQ applies the NEQ predicate on the "boardId" field.
func BoardIdNEQ(v int) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.FieldNEQ(FieldBoardId, v))
}

// BoardIdIn applies the In predicate on the "boardId" field.
func BoardIdIn(vs ...int) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.FieldIn(FieldBoardId, vs...))
}

// BoardIdNotIn applies the NotIn predicate on the "boardId" field.
func BoardIdNotIn(vs ...int) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.FieldNotIn(FieldBoardId, vs...))
}

// LikedAtEQ applies the EQ predicate on the "likedAt" field.
func LikedAtEQ(v time.Time) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.FieldEQ(FieldLikedAt, v))
}

// LikedAtNEQ applies the NEQ predicate on the "likedAt" field.
func LikedAtNEQ(v time.Time) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.FieldNEQ(FieldLikedAt, v))
}

// LikedAtIn applies the In predicate on the "likedAt" field.
func LikedAtIn(vs ...time.Time) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.FieldIn(FieldLikedAt, vs...))
}

// LikedAtNotIn applies the NotIn predicate on the "likedAt" field.
func LikedAtNotIn(vs ...time.Time) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.FieldNotIn(FieldLikedAt, vs...))
}

// LikedAtGT applies the GT predicate on the "likedAt" field.
func LikedAtGT(v time.Time) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.FieldGT(FieldLikedAt, v))
}

// LikedAtGTE applies the GTE predicate on the "likedAt" field.
func LikedAtGTE(v time.Time) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.FieldGTE(FieldLikedAt, v))
}

// LikedAtLT applies the LT predicate on the "likedAt" field.
func LikedAtLT(v time.Time) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.FieldLT(FieldLikedAt, v))
}

// LikedAtLTE applies the LTE predicate on the "likedAt" field.
func LikedAtLTE(v time.Time) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.FieldLTE(FieldLikedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserBoardLike {
	return predicate.UserBoardLike(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, UserColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserBoardLike {
	return predicate.UserBoardLike(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBoard applies the HasEdge predicate on the "board" edge.
func HasBoard() predicate.UserBoardLike {
	return predicate.UserBoardLike(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, BoardColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, BoardTable, BoardColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBoardWith applies the HasEdge predicate on the "board" edge with a given conditions (other predicates).
func HasBoardWith(preds ...predicate.Board) predicate.UserBoardLike {
	return predicate.UserBoardLike(func(s *sql.Selector) {
		step := newBoardStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserBoardLike) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserBoardLike) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserBoardLike) predicate.UserBoardLike {
	return predicate.UserBoardLike(sql.NotPredicates(p))
}
