services:
  server:
    container_name: hentai-salon-server
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    volumes:
      - ./packages/server:/server
    environment:
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    networks:
      net1:
        ipv4_address: 192.168.10.10

  client:
    container_name: hentai-salon-client
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    restart: always
    tty: true
    init: true
    ports:
      - 80:3000
    depends_on:
      - server
      - mysql
    volumes:
      - ./packages/client:/client
    networks:
      net1:
        ipv4_address: 192.168.10.30

  mysql:
    image: mysql:8.0
    container_name: hentai-salon-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    restart: always
    networks:
      net1:
        ipv4_address: 192.168.10.20

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hentai-salon-phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_ARBITRARY: '1'
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
    ports:
      - 8081:80  
    networks:
      net1:
        ipv4_address: 192.168.10.40

  # minio:
  #   image: minio/minio:latest
  #   container_name: hentai-salon-minio
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   volumes:
  #     - ./docker/minio/data:/export
  #     - ./docker/minio/config:/root/.minio
  #   environment:
  #     MINIO_ACCESS_KEY: minio_root
  #     MINIO_SECRET_KEY: minio_password
  #   command: server /export --console-address ":9001"
  #   networks:
  #     net1:
  #       ipv4_address: 192.168.10.80

  # infra:
  #   container_name: hentai-salon-infra
  #   platform: linux/x86_64
  #   build:
  #     context: .
  #     dockerfile: docker/infra/Dockerfile
  #   ports:
  #     - 22:22
  #   volumes:
  #     - ./:/infra
  #     - ~/.aws:/root/.aws:ro
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   tty: true
  #   networks:
  #     net1:
  #       ipv4_address: 192.168.10.70

networks:
  net1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
