services:
  server-app:
    container_name: hentai-salon-server-app
    image: ${ECR_SERVER_APP_URI}
    platform: linux/x86_64
    build:
      context: .
      dockerfile: docker/server/Dockerfile

  server-proxy:
    container_name: hentai-salon-server-proxy
    image: ${ECR_SERVER_PROXY_URI}
    platform: linux/x86_64
    build:
      context: .
      dockerfile: docker/nginx/client/Dockerfile

  client-app:
    container_name: hentai-salon-client-app
    image: ${ECR_CLIENT_APP_URI}
    platform: linux/x86_64
    build:
      context: .
      dockerfile: docker/client/Dockerfile

  client-proxy:
    container_name: hentai-salon-server-proxy
    image: ${ECR_CLIENT_PROXY_URI}
    platform: linux/x86_64
    build:
      context: .
      dockerfile: docker/nginx/server/Dockerfile
