services:
  server-app:
    container_name: hentai-salon-server-app
    image: ${ECR_SERVER_APP_URI}
    platform: linux/x86_64
    build:
      context: .
      dockerfile: docker/server/app/Dockerfile
      target: prd

  server-proxy:
    container_name: hentai-salon-server-proxy
    image: ${ECR_SERVER_PROXY_URI}
    platform: linux/x86_64
    build:
      context: .
      dockerfile: docker/server/proxy/Dockerfile

  client-app:
    container_name: hentai-salon-client-app
    image: ${ECR_CLIENT_APP_URI}
    platform: linux/x86_64
    build:
      context: .
      dockerfile: docker/client/app/Dockerfile
      target: prd

  client-proxy:
    container_name: hentai-salon-client-proxy
    image: ${ECR_CLIENT_PROXY_URI}
    platform: linux/x86_64
    build:
      context: .
      dockerfile: docker/client/proxy/Dockerfile
