// Code generated by ent, DO NOT EDIT.

package userboardsubscription

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the userboardsubscription type in the database.
	Label = "user_board_subscription"
	// FieldUserId holds the string denoting the userid field in the database.
	FieldUserId = "user_id"
	// FieldBoardId holds the string denoting the boardid field in the database.
	FieldBoardId = "board_id"
	// FieldIsNotified holds the string denoting the isnotified field in the database.
	FieldIsNotified = "is_notified"
	// FieldIsChecked holds the string denoting the ischecked field in the database.
	FieldIsChecked = "is_checked"
	// FieldSubscribedAt holds the string denoting the subscribedat field in the database.
	FieldSubscribedAt = "subscribed_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeBoard holds the string denoting the board edge name in mutations.
	EdgeBoard = "board"
	// UserFieldID holds the string denoting the ID field of the User.
	UserFieldID = "id"
	// BoardFieldID holds the string denoting the ID field of the Board.
	BoardFieldID = "id"
	// Table holds the table name of the userboardsubscription in the database.
	Table = "user_board_subscriptions"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_board_subscriptions"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// BoardTable is the table that holds the board relation/edge.
	BoardTable = "user_board_subscriptions"
	// BoardInverseTable is the table name for the Board entity.
	// It exists in this package in order to avoid circular dependency with the "board" package.
	BoardInverseTable = "boards"
	// BoardColumn is the table column denoting the board relation/edge.
	BoardColumn = "board_id"
)

// Columns holds all SQL columns for userboardsubscription fields.
var Columns = []string{
	FieldUserId,
	FieldBoardId,
	FieldIsNotified,
	FieldIsChecked,
	FieldSubscribedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsNotified holds the default value on creation for the "isNotified" field.
	DefaultIsNotified bool
	// DefaultIsChecked holds the default value on creation for the "isChecked" field.
	DefaultIsChecked bool
	// DefaultSubscribedAt holds the default value on creation for the "subscribedAt" field.
	DefaultSubscribedAt func() time.Time
)

// OrderOption defines the ordering options for the UserBoardSubscription queries.
type OrderOption func(*sql.Selector)

// ByUserId orders the results by the userId field.
func ByUserId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserId, opts...).ToFunc()
}

// ByBoardId orders the results by the boardId field.
func ByBoardId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBoardId, opts...).ToFunc()
}

// ByIsNotified orders the results by the isNotified field.
func ByIsNotified(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsNotified, opts...).ToFunc()
}

// ByIsChecked orders the results by the isChecked field.
func ByIsChecked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsChecked, opts...).ToFunc()
}

// BySubscribedAt orders the results by the subscribedAt field.
func BySubscribedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscribedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByBoardField orders the results by board field.
func ByBoardField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBoardStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, UserColumn),
		sqlgraph.To(UserInverseTable, UserFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
	)
}
func newBoardStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, BoardColumn),
		sqlgraph.To(BoardInverseTable, BoardFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, BoardTable, BoardColumn),
	)
}
