-- Create "users" table
CREATE TABLE `users` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(20) NOT NULL, `email` varchar(254) NOT NULL, `password` varchar(255) NOT NULL, `avatar_url` varchar(255) NULL, `status` bigint NOT NULL DEFAULT 0, `role` bigint NOT NULL DEFAULT 0, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `email` (`email`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "boards" table
CREATE TABLE `boards` (`id` bigint NOT NULL AUTO_INCREMENT, `title` varchar(50) NOT NULL, `description` varchar(255) NULL, `thumbnail_url` varchar(255) NULL, `status` bigint NOT NULL DEFAULT 0, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `user_id` bigint NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `board_title` (`title`), INDEX `boards_users_boards` (`user_id`), UNIQUE INDEX `title` (`title`), CONSTRAINT `boards_users_boards` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "threads" table
CREATE TABLE `threads` (`id` bigint NOT NULL AUTO_INCREMENT, `title` varchar(50) NOT NULL, `description` varchar(255) NULL, `thumbnail_url` varchar(255) NULL, `ip_address` varchar(64) NOT NULL, `status` bigint NOT NULL DEFAULT 0, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `board_id` bigint NOT NULL, `user_id` bigint NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `thread_title` (`title`), INDEX `threads_boards_threads` (`board_id`), INDEX `threads_users_threads` (`user_id`), UNIQUE INDEX `title` (`title`), CONSTRAINT `threads_boards_threads` FOREIGN KEY (`board_id`) REFERENCES `boards` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `threads_users_threads` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "thread_comments" table
CREATE TABLE `thread_comments` (`id` bigint NOT NULL AUTO_INCREMENT, `guest_name` varchar(20) NULL, `content` longtext NOT NULL, `ip_address` varchar(64) NOT NULL, `status` bigint NOT NULL DEFAULT 0, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `thread_id` bigint NOT NULL, `parent_comment_id` bigint NULL, `user_id` bigint NULL, PRIMARY KEY (`id`), INDEX `thread_comments_thread_comments_replies` (`parent_comment_id`), INDEX `thread_comments_threads_comments` (`thread_id`), INDEX `thread_comments_users_comments` (`user_id`), CONSTRAINT `thread_comments_thread_comments_replies` FOREIGN KEY (`parent_comment_id`) REFERENCES `thread_comments` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT `thread_comments_threads_comments` FOREIGN KEY (`thread_id`) REFERENCES `threads` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `thread_comments_users_comments` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "thread_comment_attachments" table
CREATE TABLE `thread_comment_attachments` (`id` bigint NOT NULL AUTO_INCREMENT, `url` varchar(255) NOT NULL, `display_order` bigint NOT NULL DEFAULT 0, `type` bigint NOT NULL DEFAULT 0, `created_at` timestamp NOT NULL, `comment_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `thread_comment_attachments_thread_comments_attachments` (`comment_id`), CONSTRAINT `thread_comment_attachments_thread_comments_attachments` FOREIGN KEY (`comment_id`) REFERENCES `thread_comments` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "tags" table
CREATE TABLE `tags` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(20) NOT NULL, `created_at` timestamp NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `name` (`name`), UNIQUE INDEX `tag_name` (`name`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "thread_tags" table
CREATE TABLE `thread_tags` (`thread_id` bigint NOT NULL, `tag_id` bigint NOT NULL, PRIMARY KEY (`thread_id`, `tag_id`), INDEX `thread_tags_tags_tag` (`tag_id`), CONSTRAINT `thread_tags_tags_tag` FOREIGN KEY (`tag_id`) REFERENCES `tags` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `thread_tags_threads_thread` FOREIGN KEY (`thread_id`) REFERENCES `threads` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "user_board_likes" table
CREATE TABLE `user_board_likes` (`liked_at` timestamp NOT NULL, `user_id` bigint NOT NULL, `board_id` bigint NOT NULL, PRIMARY KEY (`user_id`, `board_id`), INDEX `user_board_likes_boards_board` (`board_id`), CONSTRAINT `user_board_likes_boards_board` FOREIGN KEY (`board_id`) REFERENCES `boards` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `user_board_likes_users_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "user_board_subscriptions" table
CREATE TABLE `user_board_subscriptions` (`is_notified` bool NOT NULL DEFAULT 1, `is_checked` bool NOT NULL DEFAULT 0, `subscribed_at` timestamp NOT NULL, `user_id` bigint NOT NULL, `board_id` bigint NOT NULL, PRIMARY KEY (`user_id`, `board_id`), INDEX `user_board_subscriptions_boards_board` (`board_id`), CONSTRAINT `user_board_subscriptions_boards_board` FOREIGN KEY (`board_id`) REFERENCES `boards` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `user_board_subscriptions_users_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "user_comment_likes" table
CREATE TABLE `user_comment_likes` (`liked_at` timestamp NOT NULL, `user_id` bigint NOT NULL, `comment_id` bigint NOT NULL, PRIMARY KEY (`user_id`, `comment_id`), INDEX `user_comment_likes_thread_comments_comment` (`comment_id`), CONSTRAINT `user_comment_likes_thread_comments_comment` FOREIGN KEY (`comment_id`) REFERENCES `thread_comments` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `user_comment_likes_users_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "user_comment_subscriptions" table
CREATE TABLE `user_comment_subscriptions` (`is_notified` bool NOT NULL DEFAULT 1, `is_checked` bool NOT NULL DEFAULT 0, `subscribed_at` timestamp NOT NULL, `user_id` bigint NOT NULL, `comment_id` bigint NOT NULL, PRIMARY KEY (`user_id`, `comment_id`), INDEX `user_comment_subscriptions_thread_comments_comment` (`comment_id`), CONSTRAINT `user_comment_subscriptions_thread_comments_comment` FOREIGN KEY (`comment_id`) REFERENCES `thread_comments` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `user_comment_subscriptions_users_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "user_thread_likes" table
CREATE TABLE `user_thread_likes` (`liked_at` timestamp NOT NULL, `user_id` bigint NOT NULL, `thread_id` bigint NOT NULL, PRIMARY KEY (`user_id`, `thread_id`), INDEX `user_thread_likes_threads_thread` (`thread_id`), CONSTRAINT `user_thread_likes_threads_thread` FOREIGN KEY (`thread_id`) REFERENCES `threads` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `user_thread_likes_users_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "user_thread_subscriptions" table
CREATE TABLE `user_thread_subscriptions` (`is_notified` bool NOT NULL DEFAULT 1, `is_checked` bool NOT NULL DEFAULT 0, `subscribed_at` timestamp NOT NULL, `user_id` bigint NOT NULL, `thread_id` bigint NOT NULL, PRIMARY KEY (`user_id`, `thread_id`), INDEX `user_thread_subscriptions_threads_thread` (`thread_id`), CONSTRAINT `user_thread_subscriptions_threads_thread` FOREIGN KEY (`thread_id`) REFERENCES `threads` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `user_thread_subscriptions_users_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
