-- Create "admin_users" table
CREATE TABLE `admin_users` (`id` bigint NOT NULL AUTO_INCREMENT, `email` varchar(255) NOT NULL, `password` varchar(255) NOT NULL, `created_at` timestamp NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `email` (`email`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "users" table
CREATE TABLE `users` (`id` bigint NOT NULL AUTO_INCREMENT, `username` varchar(255) NOT NULL, `email` varchar(255) NOT NULL, `password` varchar(255) NOT NULL, `display_name` varchar(255) NULL, `avatar` varchar(255) NULL, `status` enum('Active','Withdrawn','Suspended','Inactive') NOT NULL DEFAULT "Active", `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `email` (`email`), UNIQUE INDEX `username` (`username`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "forums" table
CREATE TABLE `forums` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `description` varchar(255) NULL, `status` enum('Public','Private','Archived','Disapproved') NOT NULL DEFAULT "Public", `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `user_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `forums_users_forums` (`user_id`), CONSTRAINT `forums_users_forums` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "topics" table
CREATE TABLE `topics` (`id` bigint NOT NULL AUTO_INCREMENT, `title` varchar(255) NOT NULL, `content` longtext NOT NULL, `is_default` bool NOT NULL DEFAULT 0, `status` enum('Open','Closed','Archived','Disapproved') NOT NULL DEFAULT "Open", `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `forum_id` bigint NOT NULL, `user_id` bigint NULL, PRIMARY KEY (`id`), INDEX `topics_forums_topics` (`forum_id`), INDEX `topics_users_topics` (`user_id`), CONSTRAINT `topics_forums_topics` FOREIGN KEY (`forum_id`) REFERENCES `forums` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `topics_users_topics` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "comments" table
CREATE TABLE `comments` (`id` bigint NOT NULL AUTO_INCREMENT, `content` longtext NOT NULL, `status` enum('Visible','Hidden','Deleted','Disapproved') NOT NULL DEFAULT "Visible", `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `parent_id` bigint NULL, `topic_id` bigint NOT NULL, `user_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `comments_comments_replies` (`parent_id`), INDEX `comments_topics_comments` (`topic_id`), INDEX `comments_users_comments` (`user_id`), CONSTRAINT `comments_comments_replies` FOREIGN KEY (`parent_id`) REFERENCES `comments` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT `comments_topics_comments` FOREIGN KEY (`topic_id`) REFERENCES `topics` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `comments_users_comments` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "comment_attachments" table
CREATE TABLE `comment_attachments` (`id` bigint NOT NULL AUTO_INCREMENT, `path` varchar(255) NOT NULL, `type` enum('image','video') NOT NULL, `created_at` timestamp NOT NULL, `comment_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `comment_attachments_comments_comment_attachments` (`comment_id`), CONSTRAINT `comment_attachments_comments_comment_attachments` FOREIGN KEY (`comment_id`) REFERENCES `comments` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "comment_likes" table
CREATE TABLE `comment_likes` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `comment_id` bigint NOT NULL, `user_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `comment_likes_comments_comment_likes` (`comment_id`), INDEX `comment_likes_users_comment_likes` (`user_id`), CONSTRAINT `comment_likes_comments_comment_likes` FOREIGN KEY (`comment_id`) REFERENCES `comments` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `comment_likes_users_comment_likes` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "forum_likes" table
CREATE TABLE `forum_likes` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `forum_id` bigint NOT NULL, `user_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `forum_likes_forums_forum_likes` (`forum_id`), INDEX `forum_likes_users_forum_likes` (`user_id`), CONSTRAINT `forum_likes_forums_forum_likes` FOREIGN KEY (`forum_id`) REFERENCES `forums` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `forum_likes_users_forum_likes` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "topic_likes" table
CREATE TABLE `topic_likes` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `topic_id` bigint NOT NULL, `user_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `topic_likes_topics_topic_likes` (`topic_id`), INDEX `topic_likes_users_topic_likes` (`user_id`), CONSTRAINT `topic_likes_topics_topic_likes` FOREIGN KEY (`topic_id`) REFERENCES `topics` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `topic_likes_users_topic_likes` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "user_comment_notifications" table
CREATE TABLE `user_comment_notifications` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `comment_id` bigint NOT NULL, `user_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `user_comment_notifications_comments_user_comment_notifications` (`comment_id`), INDEX `user_comment_notifications_users_user_comment_notifications` (`user_id`), CONSTRAINT `user_comment_notifications_comments_user_comment_notifications` FOREIGN KEY (`comment_id`) REFERENCES `comments` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `user_comment_notifications_users_user_comment_notifications` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "user_topic_notifications" table
CREATE TABLE `user_topic_notifications` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` timestamp NOT NULL, `topic_id` bigint NOT NULL, `user_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `user_topic_notifications_topics_user_topic_notifications` (`topic_id`), INDEX `user_topic_notifications_users_user_topic_notifications` (`user_id`), CONSTRAINT `user_topic_notifications_topics_user_topic_notifications` FOREIGN KEY (`topic_id`) REFERENCES `topics` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `user_topic_notifications_users_user_topic_notifications` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
