-- Create "users" table
CREATE TABLE `users` (`id` bigint NOT NULL AUTO_INCREMENT, `user_name` varchar(20) NOT NULL, `email` varchar(254) NOT NULL, `password` varchar(255) NOT NULL, `display_name` varchar(20) NULL, `avatar_url` varchar(255) NULL, `status` enum('Active','Withdrawn','Suspended','Inactive') NOT NULL DEFAULT "Active", `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `email` (`email`), UNIQUE INDEX `user_name` (`user_name`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "admin_users" table
CREATE TABLE `admin_users` (`id` bigint NOT NULL AUTO_INCREMENT, `user_name` varchar(20) NOT NULL, `email` varchar(254) NOT NULL, `password` varchar(255) NOT NULL, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `email` (`email`), UNIQUE INDEX `user_name` (`user_name`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "forums" table
CREATE TABLE `forums` (`id` bigint NOT NULL AUTO_INCREMENT, `user_id` bigint NOT NULL, `title` varchar(50) NOT NULL, `description` varchar(255) NULL, `thumbnail_url` varchar(255) NULL, `status` enum('Public','Private','Archived') NOT NULL DEFAULT "Public", `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `user_forums` bigint NULL, PRIMARY KEY (`id`), INDEX `forums_users_forums` (`user_forums`), CONSTRAINT `forums_users_forums` FOREIGN KEY (`user_forums`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "topics" table
CREATE TABLE `topics` (`id` bigint NOT NULL AUTO_INCREMENT, `title` varchar(50) NULL, `description` varchar(255) NULL, `thumbnail_url` varchar(255) NULL, `is_auto_generated` bool NOT NULL DEFAULT 0, `is_notify_on_comment` bool NOT NULL DEFAULT 1, `status` enum('Open','Closed','Archived') NOT NULL DEFAULT "Open", `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `forum_id` bigint NOT NULL, `user_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `topics_forums_topics` (`forum_id`), INDEX `topics_users_topics` (`user_id`), CONSTRAINT `topics_forums_topics` FOREIGN KEY (`forum_id`) REFERENCES `forums` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `topics_users_topics` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "comments" table
CREATE TABLE `comments` (`id` bigint NOT NULL AUTO_INCREMENT, `guest_name` varchar(20) NULL, `message` longtext NOT NULL, `status` enum('Visible','Disapproved') NOT NULL DEFAULT "Visible", `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `parent_id` bigint NULL, `topic_id` bigint NOT NULL, `user_id` bigint NULL, PRIMARY KEY (`id`), INDEX `comments_comments_replies` (`parent_id`), INDEX `comments_topics_comments` (`topic_id`), INDEX `comments_users_comments` (`user_id`), CONSTRAINT `comments_comments_replies` FOREIGN KEY (`parent_id`) REFERENCES `comments` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT `comments_topics_comments` FOREIGN KEY (`topic_id`) REFERENCES `topics` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `comments_users_comments` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "comment_attachments" table
CREATE TABLE `comment_attachments` (`id` bigint NOT NULL AUTO_INCREMENT, `url` varchar(255) NOT NULL, `order` bigint NOT NULL DEFAULT 0, `type` enum('image','video') NOT NULL, `comment_id` bigint NOT NULL, PRIMARY KEY (`id`), INDEX `comment_attachments_comments_comment_attachments` (`comment_id`), CONSTRAINT `comment_attachments_comments_comment_attachments` FOREIGN KEY (`comment_id`) REFERENCES `comments` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "topic_tags" table
CREATE TABLE `topic_tags` (`id` bigint NOT NULL AUTO_INCREMENT, `name` varchar(20) NOT NULL, `created_at` timestamp NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `name` (`name`), UNIQUE INDEX `topictag_name` (`name`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "topic_taggings" table
CREATE TABLE `topic_taggings` (`topic_id` bigint NOT NULL, `tag_id` bigint NOT NULL, PRIMARY KEY (`topic_id`, `tag_id`), INDEX `topic_taggings_topic_tags_tag` (`tag_id`), CONSTRAINT `topic_taggings_topic_tags_tag` FOREIGN KEY (`tag_id`) REFERENCES `topic_tags` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `topic_taggings_topics_topic` FOREIGN KEY (`topic_id`) REFERENCES `topics` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "user_comment_likes" table
CREATE TABLE `user_comment_likes` (`type` enum('like','dislike') NOT NULL, `liked_at` timestamp NOT NULL, `user_id` bigint NOT NULL, `comment_id` bigint NOT NULL, PRIMARY KEY (`user_id`, `comment_id`), INDEX `user_comment_likes_comments_comment` (`comment_id`), CONSTRAINT `user_comment_likes_comments_comment` FOREIGN KEY (`comment_id`) REFERENCES `comments` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `user_comment_likes_users_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "user_comment_subscriptions" table
CREATE TABLE `user_comment_subscriptions` (`is_notified` bool NOT NULL DEFAULT 1, `subscribed_at` timestamp NOT NULL, `user_id` bigint NOT NULL, `comment_id` bigint NOT NULL, PRIMARY KEY (`user_id`, `comment_id`), INDEX `user_comment_subscriptions_comments_comment` (`comment_id`), CONSTRAINT `user_comment_subscriptions_comments_comment` FOREIGN KEY (`comment_id`) REFERENCES `comments` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `user_comment_subscriptions_users_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "user_forum_likes" table
CREATE TABLE `user_forum_likes` (`type` enum('like','dislike') NOT NULL, `liked_at` timestamp NOT NULL, `user_id` bigint NOT NULL, `forum_id` bigint NOT NULL, PRIMARY KEY (`user_id`, `forum_id`), INDEX `user_forum_likes_forums_forum` (`forum_id`), CONSTRAINT `user_forum_likes_forums_forum` FOREIGN KEY (`forum_id`) REFERENCES `forums` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `user_forum_likes_users_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "user_forum_subscriptions" table
CREATE TABLE `user_forum_subscriptions` (`is_notified` bool NOT NULL DEFAULT 1, `subscribed_at` timestamp NOT NULL, `user_id` bigint NOT NULL, `forum_id` bigint NOT NULL, PRIMARY KEY (`user_id`, `forum_id`), INDEX `user_forum_subscriptions_forums_forum` (`forum_id`), CONSTRAINT `user_forum_subscriptions_forums_forum` FOREIGN KEY (`forum_id`) REFERENCES `forums` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `user_forum_subscriptions_users_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "user_topic_likes" table
CREATE TABLE `user_topic_likes` (`type` enum('like','dislike') NOT NULL, `liked_at` timestamp NOT NULL, `user_id` bigint NOT NULL, `topic_id` bigint NOT NULL, PRIMARY KEY (`user_id`, `topic_id`), INDEX `user_topic_likes_topics_topic` (`topic_id`), CONSTRAINT `user_topic_likes_topics_topic` FOREIGN KEY (`topic_id`) REFERENCES `topics` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `user_topic_likes_users_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "user_topic_subscriptions" table
CREATE TABLE `user_topic_subscriptions` (`is_notified` bool NOT NULL DEFAULT 1, `subscribed_at` timestamp NOT NULL, `user_id` bigint NOT NULL, `topic_id` bigint NOT NULL, PRIMARY KEY (`user_id`, `topic_id`), INDEX `user_topic_subscriptions_topics_topic` (`topic_id`), CONSTRAINT `user_topic_subscriptions_topics_topic` FOREIGN KEY (`topic_id`) REFERENCES `topics` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `user_topic_subscriptions_users_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
