// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"server/infrastructure/ent/topic"
	"server/infrastructure/ent/topictag"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TopicTagCreate is the builder for creating a TopicTag entity.
type TopicTagCreate struct {
	config
	mutation *TopicTagMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (ttc *TopicTagCreate) SetName(s string) *TopicTagCreate {
	ttc.mutation.SetName(s)
	return ttc
}

// SetCreatedAt sets the "createdAt" field.
func (ttc *TopicTagCreate) SetCreatedAt(t time.Time) *TopicTagCreate {
	ttc.mutation.SetCreatedAt(t)
	return ttc
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (ttc *TopicTagCreate) SetNillableCreatedAt(t *time.Time) *TopicTagCreate {
	if t != nil {
		ttc.SetCreatedAt(*t)
	}
	return ttc
}

// SetID sets the "id" field.
func (ttc *TopicTagCreate) SetID(i int) *TopicTagCreate {
	ttc.mutation.SetID(i)
	return ttc
}

// AddTopicIDs adds the "topics" edge to the Topic entity by IDs.
func (ttc *TopicTagCreate) AddTopicIDs(ids ...int) *TopicTagCreate {
	ttc.mutation.AddTopicIDs(ids...)
	return ttc
}

// AddTopics adds the "topics" edges to the Topic entity.
func (ttc *TopicTagCreate) AddTopics(t ...*Topic) *TopicTagCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ttc.AddTopicIDs(ids...)
}

// Mutation returns the TopicTagMutation object of the builder.
func (ttc *TopicTagCreate) Mutation() *TopicTagMutation {
	return ttc.mutation
}

// Save creates the TopicTag in the database.
func (ttc *TopicTagCreate) Save(ctx context.Context) (*TopicTag, error) {
	ttc.defaults()
	return withHooks(ctx, ttc.sqlSave, ttc.mutation, ttc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ttc *TopicTagCreate) SaveX(ctx context.Context) *TopicTag {
	v, err := ttc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ttc *TopicTagCreate) Exec(ctx context.Context) error {
	_, err := ttc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ttc *TopicTagCreate) ExecX(ctx context.Context) {
	if err := ttc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ttc *TopicTagCreate) defaults() {
	if _, ok := ttc.mutation.CreatedAt(); !ok {
		v := topictag.DefaultCreatedAt()
		ttc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ttc *TopicTagCreate) check() error {
	if _, ok := ttc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TopicTag.name"`)}
	}
	if v, ok := ttc.mutation.Name(); ok {
		if err := topictag.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TopicTag.name": %w`, err)}
		}
	}
	if _, ok := ttc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "TopicTag.createdAt"`)}
	}
	return nil
}

func (ttc *TopicTagCreate) sqlSave(ctx context.Context) (*TopicTag, error) {
	if err := ttc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ttc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ttc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	ttc.mutation.id = &_node.ID
	ttc.mutation.done = true
	return _node, nil
}

func (ttc *TopicTagCreate) createSpec() (*TopicTag, *sqlgraph.CreateSpec) {
	var (
		_node = &TopicTag{config: ttc.config}
		_spec = sqlgraph.NewCreateSpec(topictag.Table, sqlgraph.NewFieldSpec(topictag.FieldID, field.TypeInt))
	)
	if id, ok := ttc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ttc.mutation.Name(); ok {
		_spec.SetField(topictag.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := ttc.mutation.CreatedAt(); ok {
		_spec.SetField(topictag.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := ttc.mutation.TopicsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   topictag.TopicsTable,
			Columns: topictag.TopicsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TopicTagCreateBulk is the builder for creating many TopicTag entities in bulk.
type TopicTagCreateBulk struct {
	config
	err      error
	builders []*TopicTagCreate
}

// Save creates the TopicTag entities in the database.
func (ttcb *TopicTagCreateBulk) Save(ctx context.Context) ([]*TopicTag, error) {
	if ttcb.err != nil {
		return nil, ttcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ttcb.builders))
	nodes := make([]*TopicTag, len(ttcb.builders))
	mutators := make([]Mutator, len(ttcb.builders))
	for i := range ttcb.builders {
		func(i int, root context.Context) {
			builder := ttcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TopicTagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ttcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ttcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ttcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ttcb *TopicTagCreateBulk) SaveX(ctx context.Context) []*TopicTag {
	v, err := ttcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ttcb *TopicTagCreateBulk) Exec(ctx context.Context) error {
	_, err := ttcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ttcb *TopicTagCreateBulk) ExecX(ctx context.Context) {
	if err := ttcb.Exec(ctx); err != nil {
		panic(err)
	}
}
