// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"server/infrastructure/ent/topic"
	"server/infrastructure/ent/user"
	"server/infrastructure/ent/usertopicnotification"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UserTopicNotification is the model entity for the UserTopicNotification schema.
type UserTopicNotification struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// TopicID holds the value of the "topic_id" field.
	TopicID int `json:"topic_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserTopicNotificationQuery when eager-loading is set.
	Edges        UserTopicNotificationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserTopicNotificationEdges holds the relations/edges for other nodes in the graph.
type UserTopicNotificationEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Topic holds the value of the topic edge.
	Topic *Topic `json:"topic,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserTopicNotificationEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// TopicOrErr returns the Topic value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserTopicNotificationEdges) TopicOrErr() (*Topic, error) {
	if e.Topic != nil {
		return e.Topic, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: topic.Label}
	}
	return nil, &NotLoadedError{edge: "topic"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserTopicNotification) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usertopicnotification.FieldID, usertopicnotification.FieldUserID, usertopicnotification.FieldTopicID:
			values[i] = new(sql.NullInt64)
		case usertopicnotification.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserTopicNotification fields.
func (utn *UserTopicNotification) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usertopicnotification.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			utn.ID = int(value.Int64)
		case usertopicnotification.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				utn.UserID = int(value.Int64)
			}
		case usertopicnotification.FieldTopicID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field topic_id", values[i])
			} else if value.Valid {
				utn.TopicID = int(value.Int64)
			}
		case usertopicnotification.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				utn.CreatedAt = value.Time
			}
		default:
			utn.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserTopicNotification.
// This includes values selected through modifiers, order, etc.
func (utn *UserTopicNotification) Value(name string) (ent.Value, error) {
	return utn.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserTopicNotification entity.
func (utn *UserTopicNotification) QueryUser() *UserQuery {
	return NewUserTopicNotificationClient(utn.config).QueryUser(utn)
}

// QueryTopic queries the "topic" edge of the UserTopicNotification entity.
func (utn *UserTopicNotification) QueryTopic() *TopicQuery {
	return NewUserTopicNotificationClient(utn.config).QueryTopic(utn)
}

// Update returns a builder for updating this UserTopicNotification.
// Note that you need to call UserTopicNotification.Unwrap() before calling this method if this UserTopicNotification
// was returned from a transaction, and the transaction was committed or rolled back.
func (utn *UserTopicNotification) Update() *UserTopicNotificationUpdateOne {
	return NewUserTopicNotificationClient(utn.config).UpdateOne(utn)
}

// Unwrap unwraps the UserTopicNotification entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (utn *UserTopicNotification) Unwrap() *UserTopicNotification {
	_tx, ok := utn.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserTopicNotification is not a transactional entity")
	}
	utn.config.driver = _tx.drv
	return utn
}

// String implements the fmt.Stringer.
func (utn *UserTopicNotification) String() string {
	var builder strings.Builder
	builder.WriteString("UserTopicNotification(")
	builder.WriteString(fmt.Sprintf("id=%v, ", utn.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", utn.UserID))
	builder.WriteString(", ")
	builder.WriteString("topic_id=")
	builder.WriteString(fmt.Sprintf("%v", utn.TopicID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(utn.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserTopicNotifications is a parsable slice of UserTopicNotification.
type UserTopicNotifications []*UserTopicNotification
