// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"server/infrastructure/ent/topic"
	"server/infrastructure/ent/user"
	"server/infrastructure/ent/usertopiclike"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UserTopicLike is the model entity for the UserTopicLike schema.
type UserTopicLike struct {
	config `json:"-"`
	// UserId holds the value of the "userId" field.
	UserId int `json:"userId,omitempty"`
	// TopicId holds the value of the "topicId" field.
	TopicId int `json:"topicId,omitempty"`
	// Type holds the value of the "type" field.
	Type usertopiclike.Type `json:"type,omitempty"`
	// LikedAt holds the value of the "likedAt" field.
	LikedAt time.Time `json:"likedAt,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserTopicLikeQuery when eager-loading is set.
	Edges        UserTopicLikeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserTopicLikeEdges holds the relations/edges for other nodes in the graph.
type UserTopicLikeEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Topic holds the value of the topic edge.
	Topic *Topic `json:"topic,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserTopicLikeEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// TopicOrErr returns the Topic value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserTopicLikeEdges) TopicOrErr() (*Topic, error) {
	if e.Topic != nil {
		return e.Topic, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: topic.Label}
	}
	return nil, &NotLoadedError{edge: "topic"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserTopicLike) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usertopiclike.FieldUserId, usertopiclike.FieldTopicId:
			values[i] = new(sql.NullInt64)
		case usertopiclike.FieldType:
			values[i] = new(sql.NullString)
		case usertopiclike.FieldLikedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserTopicLike fields.
func (utl *UserTopicLike) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usertopiclike.FieldUserId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field userId", values[i])
			} else if value.Valid {
				utl.UserId = int(value.Int64)
			}
		case usertopiclike.FieldTopicId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field topicId", values[i])
			} else if value.Valid {
				utl.TopicId = int(value.Int64)
			}
		case usertopiclike.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				utl.Type = usertopiclike.Type(value.String)
			}
		case usertopiclike.FieldLikedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field likedAt", values[i])
			} else if value.Valid {
				utl.LikedAt = value.Time
			}
		default:
			utl.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserTopicLike.
// This includes values selected through modifiers, order, etc.
func (utl *UserTopicLike) Value(name string) (ent.Value, error) {
	return utl.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserTopicLike entity.
func (utl *UserTopicLike) QueryUser() *UserQuery {
	return NewUserTopicLikeClient(utl.config).QueryUser(utl)
}

// QueryTopic queries the "topic" edge of the UserTopicLike entity.
func (utl *UserTopicLike) QueryTopic() *TopicQuery {
	return NewUserTopicLikeClient(utl.config).QueryTopic(utl)
}

// Update returns a builder for updating this UserTopicLike.
// Note that you need to call UserTopicLike.Unwrap() before calling this method if this UserTopicLike
// was returned from a transaction, and the transaction was committed or rolled back.
func (utl *UserTopicLike) Update() *UserTopicLikeUpdateOne {
	return NewUserTopicLikeClient(utl.config).UpdateOne(utl)
}

// Unwrap unwraps the UserTopicLike entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (utl *UserTopicLike) Unwrap() *UserTopicLike {
	_tx, ok := utl.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserTopicLike is not a transactional entity")
	}
	utl.config.driver = _tx.drv
	return utl
}

// String implements the fmt.Stringer.
func (utl *UserTopicLike) String() string {
	var builder strings.Builder
	builder.WriteString("UserTopicLike(")
	builder.WriteString("userId=")
	builder.WriteString(fmt.Sprintf("%v", utl.UserId))
	builder.WriteString(", ")
	builder.WriteString("topicId=")
	builder.WriteString(fmt.Sprintf("%v", utl.TopicId))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", utl.Type))
	builder.WriteString(", ")
	builder.WriteString("likedAt=")
	builder.WriteString(utl.LikedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserTopicLikes is a parsable slice of UserTopicLike.
type UserTopicLikes []*UserTopicLike
