// Code generated by ent, DO NOT EDIT.

package userforumlike

import (
	"server/infrastructure/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// UserId applies equality check predicate on the "userId" field. It's identical to UserIdEQ.
func UserId(v int) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldEQ(FieldUserId, v))
}

// ForumId applies equality check predicate on the "forumId" field. It's identical to ForumIdEQ.
func ForumId(v int) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldEQ(FieldForumId, v))
}

// LikedAt applies equality check predicate on the "likedAt" field. It's identical to LikedAtEQ.
func LikedAt(v time.Time) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldEQ(FieldLikedAt, v))
}

// UserIdEQ applies the EQ predicate on the "userId" field.
func UserIdEQ(v int) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldEQ(FieldUserId, v))
}

// UserIdNEQ applies the NEQ predicate on the "userId" field.
func UserIdNEQ(v int) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldNEQ(FieldUserId, v))
}

// UserIdIn applies the In predicate on the "userId" field.
func UserIdIn(vs ...int) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldIn(FieldUserId, vs...))
}

// UserIdNotIn applies the NotIn predicate on the "userId" field.
func UserIdNotIn(vs ...int) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldNotIn(FieldUserId, vs...))
}

// ForumIdEQ applies the EQ predicate on the "forumId" field.
func ForumIdEQ(v int) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldEQ(FieldForumId, v))
}

// ForumIdNEQ applies the NEQ predicate on the "forumId" field.
func ForumIdNEQ(v int) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldNEQ(FieldForumId, v))
}

// ForumIdIn applies the In predicate on the "forumId" field.
func ForumIdIn(vs ...int) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldIn(FieldForumId, vs...))
}

// ForumIdNotIn applies the NotIn predicate on the "forumId" field.
func ForumIdNotIn(vs ...int) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldNotIn(FieldForumId, vs...))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldNotIn(FieldType, vs...))
}

// LikedAtEQ applies the EQ predicate on the "likedAt" field.
func LikedAtEQ(v time.Time) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldEQ(FieldLikedAt, v))
}

// LikedAtNEQ applies the NEQ predicate on the "likedAt" field.
func LikedAtNEQ(v time.Time) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldNEQ(FieldLikedAt, v))
}

// LikedAtIn applies the In predicate on the "likedAt" field.
func LikedAtIn(vs ...time.Time) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldIn(FieldLikedAt, vs...))
}

// LikedAtNotIn applies the NotIn predicate on the "likedAt" field.
func LikedAtNotIn(vs ...time.Time) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldNotIn(FieldLikedAt, vs...))
}

// LikedAtGT applies the GT predicate on the "likedAt" field.
func LikedAtGT(v time.Time) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldGT(FieldLikedAt, v))
}

// LikedAtGTE applies the GTE predicate on the "likedAt" field.
func LikedAtGTE(v time.Time) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldGTE(FieldLikedAt, v))
}

// LikedAtLT applies the LT predicate on the "likedAt" field.
func LikedAtLT(v time.Time) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldLT(FieldLikedAt, v))
}

// LikedAtLTE applies the LTE predicate on the "likedAt" field.
func LikedAtLTE(v time.Time) predicate.UserForumLike {
	return predicate.UserForumLike(sql.FieldLTE(FieldLikedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserForumLike {
	return predicate.UserForumLike(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, UserColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserForumLike {
	return predicate.UserForumLike(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasForum applies the HasEdge predicate on the "forum" edge.
func HasForum() predicate.UserForumLike {
	return predicate.UserForumLike(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, ForumColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, ForumTable, ForumColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasForumWith applies the HasEdge predicate on the "forum" edge with a given conditions (other predicates).
func HasForumWith(preds ...predicate.Forum) predicate.UserForumLike {
	return predicate.UserForumLike(func(s *sql.Selector) {
		step := newForumStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserForumLike) predicate.UserForumLike {
	return predicate.UserForumLike(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserForumLike) predicate.UserForumLike {
	return predicate.UserForumLike(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserForumLike) predicate.UserForumLike {
	return predicate.UserForumLike(sql.NotPredicates(p))
}
